# Generated by Django 3.2.9 on 2021-11-21 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Articles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=80, null=True)),
                ('cover', models.CharField(blank=True, max_length=300, null=True)),
                ('describe', models.CharField(blank=True, max_length=300, null=True)),
                ('content', models.TextField()),
            ],
        ),
    ]
